### ISSUE TITLE
Remove autopub & insecure

### ISSUE THREAD

**Issue by queso** [D1no/TrackerReact-Meteor1.3#1]
I think you should remove these and show subscription management since this is an example app. I know the README shows it in the main repo... But still think it is better practice to show users a solid example without security holes.

**Comment by queso** [comment]
https://github.com/D1no/TrackerReact-Meteor1.3/blob/master/.meteor/packages#L18-L19

**Comment by D1no** [comment]
You're right. Now there is a proper example online. It should be much clearer now. Also, the readme syntax on TrackerReact was not completely correct yet in the constructor call. Now it's fixed.

This example is a mix of implementation instructions and a template I usually use for hires as coding exercises to see how one adapts a "foreign technology" based of existing code and documentation. Asking about optimistic updates, reactivity etc. Let me know if you think something is missing.
