### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by queso** [D1no/TrackerReact-Meteor1.3#3]
The one thing that flubbed me up with TrackerReact today was figuring out how to pass params from flow router as props and then use them during the subscribe part of the constructor with React Components.

Any thoughts on adding a router to show off that pattern? Happy to help out with some code.

**Comment by D1no** [comment]
That is a pretty good idea actually. I am not sure if we should put an opinion on routing in the example but an illustration of how to handle passed down props is probably necessary.
