### ISSUE TITLE
subscription not reactive

### ISSUE THREAD

**Issue by stocksp** [D1no/TrackerReact-Meteor1.3#5]
I have a subscription that looks like

```
state = {
    tasks: Meteor.subscribe('tasks', theApp.week.get()),
    week: theApp.week
}
```

where `theApp.week` is a reactive var.  And the week is changed through an unrelated component.
This subscription does NOT rerun when the 'week' is changed.
render does rerun,  but the subscription is not updated with the new week.
How do I get the subscription to rerun when the week is changed?

**Comment by D1no** [comment]
I'd need to take a look at it. Can you share a repo?

**Comment by D1no** [comment]
Ah, sorry, I think I have miss read your question before. Yes, reactivity is tracked on the render function. Which is perfectly fine because render here nothing to do with real rendering to the DOM. The function will run anyway. Often even on remote props changes if not manually controlled - React is different in that matter.

If you want to dynamically change the state, you could simply put a handler dependent on a reactive data source into the render function to change a state, subscriptions etc. You may want to look into the example how the "toggleSubscrption" was done.

**Comment by stocksp** [comment]
I'm a little confused here.
I need the subscription  to rerun.  and it does not
Its not clear to me how to make this work.
The above subscription works and reruns using getMeteorData.
theApp.week is a reactive data source.
The actual subscription looks like this
`handleData: Meteor.subscribe('tasks', theApp.week.get())`
I check handleData.ready() in the render method and if the data is there I use it.
Your example code shows the subscription being changed from a local method.
I only have a reactive data sourse  theApp.week.  I'm not able to get the subscription to use it reactively.   The subscription only runs once  it needs to rerun everytime theApp.week changes.
The change happens from an unrelated component.
If I have time tomorrow I'll hack your sample into a repo.

**Comment by stocksp** [comment]
I reread your comment.
I removed ALL state.  Put my subscriptions at the top of render.
So my render looks like:

```
render() {
    const league = FlowRouter.current().params.league;
    const handleWeeks = Meteor.subscribe('weeks', league)
    const handleData = Meteor.subscribe('sheetData', league, 'high', theApp.week.get());
    if (handleData.ready() && handleWeeks.ready()) {
    ...
```

It works GREAT!   It 'feels' a little strange putting my subscriptions in render and removing the state object... but it seems to work very nicely...  and this now is by far the simplest/cleanest implementation of Meteor React 1.3 I've tried.   This app is a Frankenstein with 4 different implementations (Mantra, getMeteorData, meteor-react-boiler-plate (Redux), and this baby.  They all work ... this is by far easiest to 'reason' about.
Thanks for all your work putting this together!!

**Comment by Yonben** [comment]
Hi,
Sorry to use an old issue to ask, but I noticed this issue is referenced whenever the "reactive subscription" issues show up. 
Anyway, I wanted to know what would be the best to ensure the subscriptions stop when using this method ?

Thanks !
